coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 2%
    patch:
      default:
        target: 80%
        informational: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

ignore:
  - "src/**/*.test.ts"
  - "src/**/*.test.tsx"
  - "src/components/**"
  - "src/stores/licenseStore.ts"
  - "src/stores/updateStore.ts"
  - "src/types/appRoute.ts"
  - "src/types/interfaces.ts"
  - "src/types/license.ts"
  - "src/vite-env.d.ts"
  - "src/main.tsx"
  - "src/App.tsx"
  - "src/test-helpers.ts"
